# -*- coding: utf-8 -*-
"""Контент курса катаканы (SRS.md, раздел 2.2).

Вводится после хираганы. Специфика: упор на гайрайго (катакана сразу
даёт «полезные» слова), правило долготы через ー, отдельный тренажёр
«катакана-ад» (シ/ツ, ソ/ン, ク/ワ/フ). 104 графемы, 18 микроуроков.
"""

KANA = [
    # --- ア行 ---
    {"char": "ア", "romaji": "a",   "kind": "basic", "row": "a",  "mnemonic": "Топорик: рукоять и лезвие — «А!»", "mnemonics": ["Растяжка ноги в шпагате — «А!»"], "lookalikes": ["マ", "ヤ"]},
    {"char": "イ", "romaji": "i",   "kind": "basic", "row": "a",  "mnemonic": "Человек прислонился к стене — «И»", "mnemonics": ["Две иголки-чёрточки — «И-и»"], "lookalikes": ["ト", "リ"]},
    {"char": "ウ", "romaji": "u",   "kind": "basic", "row": "a",  "mnemonic": "Крыша с трубой — как う без хвоста", "mnemonics": ["Зонтик раскрылся — «У»"], "lookalikes": ["ワ", "フ"]},
    {"char": "エ", "romaji": "e",   "kind": "basic", "row": "a",  "mnemonic": "Двутавровая балка — «Э»", "mnemonics": ["Кандзи 工 (работа) — «Э»"], "lookalikes": ["ユ", "ヨ"]},
    {"char": "オ", "romaji": "o",   "kind": "basic", "row": "a",  "mnemonic": "Мачта с флагом на ветру — «О!»", "mnemonics": ["Крючок с перекладиной — «О!»"], "lookalikes": ["ヲ", "ホ"]},
    # --- カ行 ---
    {"char": "カ", "romaji": "ka",  "kind": "basic", "row": "ka", "mnemonic": "Как хирагана か, но без хвостика", "mnemonics": ["Косарь взмахнул серпом — «КА»"], "lookalikes": ["タ", "ヤ"]},
    {"char": "キ", "romaji": "ki",  "kind": "basic", "row": "ka", "mnemonic": "Ключ — верх от хираганы き", "mnemonics": ["Колосок с двумя усиками — «КИ»"], "lookalikes": ["チ", "サ"]},
    {"char": "ク", "romaji": "ku",  "kind": "basic", "row": "ka", "mnemonic": "Клюв чайки в полёте", "mnemonics": ["Уголок «больше» (>) — «КУ»"], "lookalikes": ["ワ", "フ", "タ"]},
    {"char": "ケ", "romaji": "ke",  "kind": "basic", "row": "ka", "mnemonic": "Косая полка на кронштейне — «КЭ»", "mnemonics": ["Кран-балка с подвесом — «КЭ»"], "lookalikes": ["ク", "タ"]},
    {"char": "コ", "romaji": "ko",  "kind": "basic", "row": "ka", "mnemonic": "Угол КОробки — два борта", "mnemonics": ["Квадратная скобка [ — «КО»"], "lookalikes": ["ユ", "ロ"]},
    # --- サ行 ---
    {"char": "サ", "romaji": "sa",  "kind": "basic", "row": "sa", "mnemonic": "Перевёрнутая вешалка — «СА»", "mnemonics": ["Кактус с двумя ветками — «СА»"], "lookalikes": ["セ", "キ"]},
    {"char": "シ", "romaji": "shi", "kind": "basic", "row": "sa", "mnemonic": "Улыбка и две реснички: черты ЛЕЖАТ, взмах снизу ВВЕРХ", "mnemonics": ["Капли летят ВВЕРХ-вбок, росчерк снизу — «ШИ»"], "lookalikes": ["ツ", "ソ", "ン"]},
    {"char": "ス", "romaji": "su",  "kind": "basic", "row": "sa", "mnemonic": "Складной СтУл, вид сбоку", "mnemonics": ["Горка с трамплином — «СУ»"], "lookalikes": ["ヌ", "フ"]},
    {"char": "セ", "romaji": "se",  "kind": "basic", "row": "sa", "mnemonic": "Как хирагана せ без нижней дуги", "mnemonics": ["Серп с короткой рукоятью — «СЭ»"], "lookalikes": ["サ", "ヒ"]},
    {"char": "ソ", "romaji": "so",  "kind": "basic", "row": "sa", "mnemonic": "Одна ресничка, черта СТОИТ и падает сверху ВНИЗ", "mnemonics": ["Капля сорвалась ВНИЗ, одна чёрточка — «СО»"], "lookalikes": ["ン", "シ", "リ"]},
    # --- タ行 ---
    {"char": "タ", "romaji": "ta",  "kind": "basic", "row": "ta", "mnemonic": "Чайка ク с глазом — «ТА»", "mnemonics": ["Месяц с точкой-звездой — «ТА»"], "lookalikes": ["ク", "ケ"]},
    {"char": "チ", "romaji": "chi", "kind": "basic", "row": "ta", "mnemonic": "Как кандзи 千 (тысяча) — «ЧИ»", "mnemonics": ["Антенна с двумя перекладинами — «ЧИ»"], "lookalikes": ["テ", "キ"]},
    {"char": "ツ", "romaji": "tsu", "kind": "basic", "row": "ta", "mnemonic": "Две капли ЦУнами: черты СТОЯТ, волна сверху ВНИЗ", "mnemonics": ["Две капли падают ВНИЗ, росчерк сбоку — «ЦУ»"], "lookalikes": ["シ", "ソ", "ン"]},
    {"char": "テ", "romaji": "te",  "kind": "basic", "row": "ta", "mnemonic": "ТЕлеграфный столб с двумя перекладинами", "mnemonics": ["Вешалка с двумя планками — «ТЭ»"], "lookalikes": ["チ", "デ"]},
    {"char": "ト", "romaji": "to",  "kind": "basic", "row": "ta", "mnemonic": "Зарубка ТОпором на столбе", "mnemonics": ["Гвоздь, вбитый сбоку — «ТО»"], "lookalikes": ["イ", "リ"]},
    # --- ナ行 ---
    {"char": "ナ", "romaji": "na",  "kind": "basic", "row": "na", "mnemonic": "Крест с длинной НАклонной ногой", "mnemonics": ["Кандзи 十 с наклоном — «НА»"], "lookalikes": ["メ", "ト"]},
    {"char": "ニ", "romaji": "ni",  "kind": "basic", "row": "na", "mnemonic": "Кандзи 二 (два) — «НИ»", "mnemonics": ["Две полки-перекладины — «НИ»"], "lookalikes": ["ミ", "コ"]},
    {"char": "ヌ", "romaji": "nu",  "kind": "basic", "row": "na", "mnemonic": "ク с перекладиной — НУ и узел!", "mnemonics": ["Перечёркнутый нож — «НУ»"], "lookalikes": ["ス", "メ"]},
    {"char": "ネ", "romaji": "ne",  "kind": "basic", "row": "na", "mnemonic": "Столбик с крестиком и подпоркой — «НЭ»", "mnemonics": ["Флагшток с косынкой — «НЭ»"], "lookalikes": ["ホ", "オ"]},
    {"char": "ノ", "romaji": "no",  "kind": "basic", "row": "na", "mnemonic": "НОж — один косой срез", "mnemonics": ["Косая черта сверху вниз — «НО»"], "lookalikes": ["メ", "ソ"]},
    # --- ハ行 ---
    {"char": "ハ", "romaji": "ha",  "kind": "basic", "row": "ha", "mnemonic": "Кандзи 八 (восемь) — две створки ворот", "mnemonics": ["Шалаш из двух жердей — «ХА»"], "lookalikes": ["リ", "ソ"]},
    {"char": "ヒ", "romaji": "hi",  "kind": "basic", "row": "ha", "mnemonic": "ХИоккейная клюшка у борта", "mnemonics": ["Каблук-шпилька — «ХИ»"], "lookalikes": ["セ", "コ"]},
    {"char": "フ", "romaji": "fu",  "kind": "basic", "row": "ha", "mnemonic": "Флаг на ФУрштоке", "mnemonics": ["Нос самолёта в пике — «ФУ»"], "lookalikes": ["ワ", "ウ", "ク"]},
    {"char": "ヘ", "romaji": "he",  "kind": "basic", "row": "ha", "mnemonic": "Холмик — почти как хирагана へ", "mnemonics": ["Крыло чайки в полёте — «ХЭ»"], "lookalikes": ["レ", "フ"]},
    {"char": "ホ", "romaji": "ho",  "kind": "basic", "row": "ha", "mnemonic": "Столб с подпорками — «ХО»", "mnemonics": ["Кандзи 木 (дерево) с засечками — «ХО»"], "lookalikes": ["ネ", "オ"]},
    # --- マ行 ---
    {"char": "マ", "romaji": "ma",  "kind": "basic", "row": "ma", "mnemonic": "МАчта с косым парусом", "mnemonics": ["Галочка с хвостиком — «МА»"], "lookalikes": ["ア", "ム"]},
    {"char": "ミ", "romaji": "mi",  "kind": "basic", "row": "ma", "mnemonic": "Три удара МИнутной стрелки", "mnemonics": ["Кандзи 三 (три) наклонно — «МИ»"], "lookalikes": ["ニ", "シ"]},
    {"char": "ム", "romaji": "mu",  "kind": "basic", "row": "ma", "mnemonic": "МУсорный совок с ручкой", "mnemonics": ["Палатка с откинутым входом — «МУ»"], "lookalikes": ["マ", "ア"]},
    {"char": "メ", "romaji": "me",  "kind": "basic", "row": "ma", "mnemonic": "Крестик-МЕтка на карте", "mnemonics": ["Скрещённые мечи — «МЭ»"], "lookalikes": ["ヌ", "ナ", "ノ"]},
    {"char": "モ", "romaji": "mo",  "kind": "basic", "row": "ma", "mnemonic": "Как хирагана も без хвоста — «МО»", "mnemonics": ["Крючок на двух перекладинах — «МО»"], "lookalikes": ["キ", "ミ"]},
    # --- ヤ行 ---
    {"char": "ヤ", "romaji": "ya",  "kind": "basic", "row": "ya", "mnemonic": "Как хирагана や — рогатка «Я!»", "mnemonics": ["Ветка с почкой — «Я»"], "lookalikes": ["ア", "カ"]},
    {"char": "ユ", "romaji": "yu",  "kind": "basic", "row": "ya", "mnemonic": "Крюк подъёмного крана — «Ю»", "mnemonics": ["Скоба с плоским дном — «Ю»"], "lookalikes": ["コ", "ヨ"]},
    {"char": "ヨ", "romaji": "yo",  "kind": "basic", "row": "ya", "mnemonic": "Грабли зубьями влево — «Ё»", "mnemonics": ["Буква Е, повёрнутая боком — «ЙО»"], "lookalikes": ["ユ", "コ"]},
    # --- ラ行 ---
    {"char": "ラ", "romaji": "ra",  "kind": "basic", "row": "ra", "mnemonic": "Фуражка с козырьком — «РА»", "mnemonics": ["Флажок на двух планках — «РА»"], "lookalikes": ["ウ", "フ"]},
    {"char": "リ", "romaji": "ri",  "kind": "basic", "row": "ra", "mnemonic": "Как хирагана り — две травинки РИса", "mnemonics": ["Две палочки разной длины — «РИ»"], "lookalikes": ["イ", "ソ"]},
    {"char": "ル", "romaji": "ru",  "kind": "basic", "row": "ra", "mnemonic": "Корни дерева расходятся — «РУ»", "mnemonics": ["Две ноги в беге — «РУ»"], "lookalikes": ["レ", "リ"]},
    {"char": "レ", "romaji": "re",  "kind": "basic", "row": "ra", "mnemonic": "Лезвие конька — «РЭ»", "mnemonics": ["Галочка «проверено» — «РЭ»"], "lookalikes": ["ル", "ノ"]},
    {"char": "ロ", "romaji": "ro",  "kind": "basic", "row": "ra", "mnemonic": "РОт — квадратное окно (кандзи 口)", "mnemonics": ["Пустая коробка-квадрат — «РО»"], "lookalikes": ["コ", "ユ"]},
    # --- ワ行 + ン ---
    {"char": "ワ", "romaji": "wa",  "kind": "basic", "row": "wa", "mnemonic": "Широкая крыша — «ВА» (как ウ без трубы)", "mnemonics": ["Распахнутый воротник — «ВА»"], "lookalikes": ["ク", "フ", "ウ"]},
    {"char": "ヲ", "romaji": "wo",  "kind": "basic", "row": "wa", "mnemonic": "フ с чертой — «ВО» (почти не встречается)", "mnemonics": ["Вешалка с перекладиной — «ВО»"], "lookalikes": ["ラ", "フ"], "note": "В современных текстах частица を пишется хираганой; ヲ встречается в основном в старых играх и вывесках."},
    {"char": "ン", "romaji": "n",   "kind": "basic", "row": "wa", "mnemonic": "Одна ресничка, взмах снизу ВВЕРХ — не путать с ソ!", "mnemonics": ["Росчерк снизу ВВЕРХ (родня シ) — «Н»"], "lookalikes": ["ソ", "シ", "ツ"]},
    # --- дакутэн: ガ行 ---
    {"char": "ガ", "romaji": "ga", "kind": "dakuten", "row": "ga", "base": "カ", "lookalikes": ["カ", "バ"]},
    {"char": "ギ", "romaji": "gi", "kind": "dakuten", "row": "ga", "base": "キ", "lookalikes": ["キ", "サ"]},
    {"char": "グ", "romaji": "gu", "kind": "dakuten", "row": "ga", "base": "ク", "lookalikes": ["ク", "ブ"]},
    {"char": "ゲ", "romaji": "ge", "kind": "dakuten", "row": "ga", "base": "ケ", "lookalikes": ["ケ", "バ"]},
    {"char": "ゴ", "romaji": "go", "kind": "dakuten", "row": "ga", "base": "コ", "lookalikes": ["コ", "ザ"]},
    # --- дакутэн: ザ行 ---
    {"char": "ザ", "romaji": "za", "kind": "dakuten", "row": "za", "base": "サ", "lookalikes": ["サ", "ギ"]},
    {"char": "ジ", "romaji": "ji", "kind": "dakuten", "row": "za", "base": "シ", "lookalikes": ["シ", "ヂ"]},
    {"char": "ズ", "romaji": "zu", "kind": "dakuten", "row": "za", "base": "ス", "lookalikes": ["ス", "ヅ"]},
    {"char": "ゼ", "romaji": "ze", "kind": "dakuten", "row": "za", "base": "セ", "lookalikes": ["セ", "パ"]},
    {"char": "ゾ", "romaji": "zo", "kind": "dakuten", "row": "za", "base": "ソ", "lookalikes": ["ソ", "ド"]},
    # --- дакутэн: ダ行 ---
    {"char": "ダ", "romaji": "da", "kind": "dakuten", "row": "da", "base": "タ", "lookalikes": ["タ", "ナ"]},
    {"char": "ヂ", "romaji": "ji (di)", "kind": "dakuten", "row": "da", "base": "チ", "lookalikes": ["チ", "ジ"], "note": "Редкий знак: тот же звук, что ジ."},
    {"char": "ヅ", "romaji": "zu (du)", "kind": "dakuten", "row": "da", "base": "ツ", "lookalikes": ["ツ", "ズ"], "note": "Редкий знак: тот же звук, что ズ."},
    {"char": "デ", "romaji": "de", "kind": "dakuten", "row": "da", "base": "テ", "lookalikes": ["テ", "ゼ"]},
    {"char": "ド", "romaji": "do", "kind": "dakuten", "row": "da", "base": "ト", "lookalikes": ["ト", "ゾ"]},
    # --- дакутэн: バ行 ---
    {"char": "バ", "romaji": "ba", "kind": "dakuten", "row": "ba", "base": "ハ", "lookalikes": ["ハ", "パ", "ボ"]},
    {"char": "ビ", "romaji": "bi", "kind": "dakuten", "row": "ba", "base": "ヒ", "lookalikes": ["ヒ", "ピ"]},
    {"char": "ブ", "romaji": "bu", "kind": "dakuten", "row": "ba", "base": "フ", "lookalikes": ["フ", "プ"]},
    {"char": "ベ", "romaji": "be", "kind": "dakuten", "row": "ba", "base": "ヘ", "lookalikes": ["ヘ", "ペ"]},
    {"char": "ボ", "romaji": "bo", "kind": "dakuten", "row": "ba", "base": "ホ", "lookalikes": ["ホ", "ポ", "バ"]},
    # --- хандакутэн: パ行 ---
    {"char": "パ", "romaji": "pa", "kind": "handakuten", "row": "pa", "base": "ハ", "lookalikes": ["ハ", "バ"]},
    {"char": "ピ", "romaji": "pi", "kind": "handakuten", "row": "pa", "base": "ヒ", "lookalikes": ["ヒ", "ビ"]},
    {"char": "プ", "romaji": "pu", "kind": "handakuten", "row": "pa", "base": "フ", "lookalikes": ["フ", "ブ"]},
    {"char": "ペ", "romaji": "pe", "kind": "handakuten", "row": "pa", "base": "ヘ", "lookalikes": ["ヘ", "ベ"]},
    {"char": "ポ", "romaji": "po", "kind": "handakuten", "row": "pa", "base": "ホ", "lookalikes": ["ホ", "ボ"]},
    # --- ёон: базовые ---
    {"char": "キャ", "romaji": "kya", "kind": "yoon", "row": "yoon1", "base": "キ", "lookalikes": ["キュ", "キョ", "チャ"]},
    {"char": "キュ", "romaji": "kyu", "kind": "yoon", "row": "yoon1", "base": "キ", "lookalikes": ["キャ", "キョ", "チュ"]},
    {"char": "キョ", "romaji": "kyo", "kind": "yoon", "row": "yoon1", "base": "キ", "lookalikes": ["キャ", "キュ", "チョ"]},
    {"char": "シャ", "romaji": "sha", "kind": "yoon", "row": "yoon1", "base": "シ", "lookalikes": ["シュ", "ショ", "チャ"]},
    {"char": "シュ", "romaji": "shu", "kind": "yoon", "row": "yoon1", "base": "シ", "lookalikes": ["シャ", "ショ", "チュ"]},
    {"char": "ショ", "romaji": "sho", "kind": "yoon", "row": "yoon1", "base": "シ", "lookalikes": ["シャ", "シュ", "チョ"]},
    {"char": "チャ", "romaji": "cha", "kind": "yoon", "row": "yoon1", "base": "チ", "lookalikes": ["チュ", "チョ", "シャ"]},
    {"char": "チュ", "romaji": "chu", "kind": "yoon", "row": "yoon1", "base": "チ", "lookalikes": ["チャ", "チョ", "シュ"]},
    {"char": "チョ", "romaji": "cho", "kind": "yoon", "row": "yoon1", "base": "チ", "lookalikes": ["チャ", "チュ", "ショ"]},
    {"char": "ニャ", "romaji": "nya", "kind": "yoon", "row": "yoon1", "base": "ニ", "lookalikes": ["ニュ", "ニョ", "ミャ"]},
    {"char": "ニュ", "romaji": "nyu", "kind": "yoon", "row": "yoon1", "base": "ニ", "lookalikes": ["ニャ", "ニョ", "ミュ"]},
    {"char": "ニョ", "romaji": "nyo", "kind": "yoon", "row": "yoon1", "base": "ニ", "lookalikes": ["ニャ", "ニュ", "ミョ"]},
    {"char": "ヒャ", "romaji": "hya", "kind": "yoon", "row": "yoon2", "base": "ヒ", "lookalikes": ["ヒュ", "ヒョ", "ビャ"]},
    {"char": "ヒュ", "romaji": "hyu", "kind": "yoon", "row": "yoon2", "base": "ヒ", "lookalikes": ["ヒャ", "ヒョ", "ビュ"]},
    {"char": "ヒョ", "romaji": "hyo", "kind": "yoon", "row": "yoon2", "base": "ヒ", "lookalikes": ["ヒャ", "ヒュ", "ビョ"]},
    {"char": "ミャ", "romaji": "mya", "kind": "yoon", "row": "yoon2", "base": "ミ", "lookalikes": ["ミュ", "ミョ", "ニャ"]},
    {"char": "ミュ", "romaji": "myu", "kind": "yoon", "row": "yoon2", "base": "ミ", "lookalikes": ["ミャ", "ミョ", "ニュ"]},
    {"char": "ミョ", "romaji": "myo", "kind": "yoon", "row": "yoon2", "base": "ミ", "lookalikes": ["ミャ", "ミュ", "ニョ"]},
    {"char": "リャ", "romaji": "rya", "kind": "yoon", "row": "yoon2", "base": "リ", "lookalikes": ["リュ", "リョ", "キャ"]},
    {"char": "リュ", "romaji": "ryu", "kind": "yoon", "row": "yoon2", "base": "リ", "lookalikes": ["リャ", "リョ", "キュ"]},
    {"char": "リョ", "romaji": "ryo", "kind": "yoon", "row": "yoon2", "base": "リ", "lookalikes": ["リャ", "リュ", "キョ"]},
    # --- ёон: дакутэн ---
    {"char": "ギャ", "romaji": "gya", "kind": "yoon", "row": "yoon3", "base": "ギ", "lookalikes": ["ギュ", "ギョ", "キャ"]},
    {"char": "ギュ", "romaji": "gyu", "kind": "yoon", "row": "yoon3", "base": "ギ", "lookalikes": ["ギャ", "ギョ", "キュ"]},
    {"char": "ギョ", "romaji": "gyo", "kind": "yoon", "row": "yoon3", "base": "ギ", "lookalikes": ["ギャ", "ギュ", "キョ"]},
    {"char": "ジャ", "romaji": "ja",  "kind": "yoon", "row": "yoon3", "base": "ジ", "lookalikes": ["ジュ", "ジョ", "シャ"]},
    {"char": "ジュ", "romaji": "ju",  "kind": "yoon", "row": "yoon3", "base": "ジ", "lookalikes": ["ジャ", "ジョ", "シュ"]},
    {"char": "ジョ", "romaji": "jo",  "kind": "yoon", "row": "yoon3", "base": "ジ", "lookalikes": ["ジャ", "ジュ", "ショ"]},
    {"char": "ビャ", "romaji": "bya", "kind": "yoon", "row": "yoon3", "base": "ビ", "lookalikes": ["ビュ", "ビョ", "ピャ"]},
    {"char": "ビュ", "romaji": "byu", "kind": "yoon", "row": "yoon3", "base": "ビ", "lookalikes": ["ビャ", "ビョ", "ピュ"]},
    {"char": "ビョ", "romaji": "byo", "kind": "yoon", "row": "yoon3", "base": "ビ", "lookalikes": ["ビャ", "ビュ", "ピョ"]},
    {"char": "ピャ", "romaji": "pya", "kind": "yoon", "row": "yoon3", "base": "ピ", "lookalikes": ["ピュ", "ピョ", "ビャ"]},
    {"char": "ピュ", "romaji": "pyu", "kind": "yoon", "row": "yoon3", "base": "ピ", "lookalikes": ["ピャ", "ピョ", "ビュ"]},
    {"char": "ピョ", "romaji": "pyo", "kind": "yoon", "row": "yoon3", "base": "ピ", "lookalikes": ["ピャ", "ピュ", "ビョ"]},
]

# «Катакана-ад» (раздел 2.2): обязательные дриллы похожих знаков
TRAP_GROUPS = [
    ["シ", "ツ"],
    ["ソ", "ン"],
    ["ク", "ワ", "フ"],
    ["チ", "テ"],
    ["ヌ", "ス"],
    ["ロ", "コ", "ユ"],
    ["マ", "ア"],
    ["ウ", "ワ"],
]

# Гайрайго: только из изученной к уроку каны; ー вводится в k01
WORDS = {
    "k01": [
        {"kana": "アイ", "romaji": "ai (AI)", "ru": "искусственный интеллект"},
        {"kana": "エア", "romaji": "ea (air)", "ru": "воздух, эйр-"},
    ],
    "k02": [
        {"kana": "カカオ", "romaji": "kakao",  "ru": "какао"},
        {"kana": "ケーキ", "romaji": "kēki",   "ru": "торт (cake)"},
        {"kana": "エコー", "romaji": "ekō",    "ru": "эхо"},
        {"kana": "カー",  "romaji": "kā",     "ru": "автомобиль (car)"},
    ],
    "k03": [
        {"kana": "アイス",  "romaji": "aisu",    "ru": "мороженое (ice)"},
        {"kana": "ソース",  "romaji": "sōsu",    "ru": "соус"},
        {"kana": "スイス",  "romaji": "suisu",   "ru": "Швейцария"},
        {"kana": "サーカス", "romaji": "sākasu",  "ru": "цирк"},
        {"kana": "シーソー", "romaji": "shīsō",   "ru": "качели-балансир"},
    ],
    "k04": [
        {"kana": "テスト",  "romaji": "tesuto",   "ru": "тест"},
        {"kana": "タクシー", "romaji": "takushī",  "ru": "такси"},
        {"kana": "トースト", "romaji": "tōsuto",   "ru": "тост (хлеб)"},
        {"kana": "テキスト", "romaji": "tekisuto", "ru": "текст, учебник"},
        {"kana": "タコス",  "romaji": "takosu",   "ru": "тако"},
        {"kana": "チーター", "romaji": "chītā",    "ru": "гепард"},
    ],
    "k05": [
        {"kana": "テニス", "romaji": "tenisu", "ru": "теннис"},
        {"kana": "ノート", "romaji": "nōto",   "ru": "тетрадь, ноут"},
        {"kana": "カヌー", "romaji": "kanū",   "ru": "каноэ"},
        {"kana": "ソナタ", "romaji": "sonata", "ru": "соната"},
        {"kana": "ナース", "romaji": "nāsu",   "ru": "медсестра (nurse)"},
    ],
    "k06": [
        {"kana": "コーヒー", "romaji": "kōhī",   "ru": "кофе"},
        {"kana": "ハート",  "romaji": "hāto",   "ru": "сердце (heart)"},
        {"kana": "ヒーター", "romaji": "hītā",   "ru": "обогреватель"},
        {"kana": "ハウス",  "romaji": "hausu",  "ru": "дом (house)"},
        {"kana": "ホース",  "romaji": "hōsu",   "ru": "шланг"},
    ],
    "k07": [
        {"kana": "メモ",  "romaji": "memo",   "ru": "заметка"},
        {"kana": "トマト", "romaji": "tomato", "ru": "помидор"},
        {"kana": "マイク", "romaji": "maiku",  "ru": "микрофон"},
        {"kana": "ハム",  "romaji": "hamu",   "ru": "ветчина"},
        {"kana": "ミニ",  "romaji": "mini",   "ru": "мини"},
        {"kana": "ムース", "romaji": "mūsu",   "ru": "мусс"},
    ],
    "k08": [
        {"kana": "タイヤ",  "romaji": "taiya",  "ru": "шина"},
        {"kana": "ユーモア", "romaji": "yūmoa",  "ru": "юмор"},
        {"kana": "ヨーヨー", "romaji": "yōyō",   "ru": "йо-йо"},
    ],
    "k09": [
        {"kana": "ホテル",  "romaji": "hoteru",  "ru": "отель"},
        {"kana": "ミルク",  "romaji": "miruku",  "ru": "молоко (milk)"},
        {"kana": "カメラ",  "romaji": "kamera",  "ru": "фотоаппарат"},
        {"kana": "ロシア",  "romaji": "roshia",  "ru": "Россия"},
        {"kana": "リレー",  "romaji": "rirē",    "ru": "эстафета"},
        {"kana": "レシート", "romaji": "reshīto", "ru": "чек (receipt)"},
    ],
    "k10": [
        {"kana": "ワイン",  "romaji": "wain",    "ru": "вино"},
        {"kana": "ラーメン", "romaji": "rāmen",   "ru": "рамен"},
        {"kana": "レモン",  "romaji": "remon",   "ru": "лимон"},
        {"kana": "メロン",  "romaji": "meron",   "ru": "дыня"},
        {"kana": "アイロン", "romaji": "airon",   "ru": "утюг (iron)"},
    ],
    "k11": [
        {"kana": "ガス",  "romaji": "gasu",   "ru": "газ"},
        {"kana": "サイズ", "romaji": "saizu",  "ru": "размер"},
        {"kana": "ゼロ",  "romaji": "zero",   "ru": "ноль"},
        {"kana": "ギター", "romaji": "gitā",   "ru": "гитара"},
        {"kana": "ゾーン", "romaji": "zōn",    "ru": "зона"},
        {"kana": "クイズ", "romaji": "kuizu",  "ru": "викторина (quiz)"},
    ],
    "k12": [
        {"kana": "ダンス",  "romaji": "dansu",   "ru": "танец"},
        {"kana": "バス",   "romaji": "basu",    "ru": "автобус"},
        {"kana": "サラダ",  "romaji": "sarada",  "ru": "салат"},
        {"kana": "バナナ",  "romaji": "banana",  "ru": "банан"},
        {"kana": "ビール",  "romaji": "bīru",    "ru": "пиво"},
        {"kana": "ドア",   "romaji": "doa",     "ru": "дверь"},
        {"kana": "デザート", "romaji": "dezāto",  "ru": "десерт"},
    ],
    "k13": [
        {"kana": "パン",   "romaji": "pan",     "ru": "хлеб"},
        {"kana": "ピアノ",  "romaji": "piano",   "ru": "пианино"},
        {"kana": "パスタ",  "romaji": "pasuta",  "ru": "паста"},
        {"kana": "プリン",  "romaji": "purin",   "ru": "пудинг"},
        {"kana": "ペン",   "romaji": "pen",     "ru": "ручка"},
        {"kana": "パンダ",  "romaji": "panda",   "ru": "панда"},
        {"kana": "ポスター", "romaji": "posutā",  "ru": "постер"},
    ],
    "k14": [
        {"kana": "ニュース",  "romaji": "nyūsu",    "ru": "новости"},
        {"kana": "シャワー",  "romaji": "shawā",    "ru": "душ"},
        {"kana": "チャンス",  "romaji": "chansu",   "ru": "шанс"},
        {"kana": "シャツ",   "romaji": "shatsu",   "ru": "рубашка"},
        {"kana": "キャベツ",  "romaji": "kyabetsu", "ru": "капуста"},
        {"kana": "チャーハン", "romaji": "chāhan",   "ru": "жареный рис"},
    ],
    "k15": [
        {"kana": "ミャンマー", "romaji": "myanmā",  "ru": "Мьянма"},
        {"kana": "ヒューマン", "romaji": "hyūman",  "ru": "человеческий (human)"},
        {"kana": "ニュアンス", "romaji": "nyuansu", "ru": "нюанс"},
    ],
    "k16": [
        {"kana": "ジュース",  "romaji": "jūsu",    "ru": "сок"},
        {"kana": "ジャム",   "romaji": "jamu",    "ru": "джем"},
        {"kana": "ジョーク",  "romaji": "jōku",    "ru": "шутка"},
        {"kana": "ジャズ",   "romaji": "jazu",    "ru": "джаз"},
        {"kana": "ギャラリー", "romaji": "gyararī", "ru": "галерея"},
        {"kana": "ピュア",   "romaji": "pyua",    "ru": "чистый (pure)"},
    ],
    "k17": [
        {"kana": "カップ",  "romaji": "kappu",   "ru": "чашка"},
        {"kana": "サッカー", "romaji": "sakkā",   "ru": "футбол"},
        {"kana": "クッキー", "romaji": "kukkī",   "ru": "печенье"},
        {"kana": "ポケット", "romaji": "poketto", "ru": "карман"},
        {"kana": "ロケット", "romaji": "roketto", "ru": "ракета"},
        {"kana": "ベッド",  "romaji": "beddo",   "ru": "кровать"},
        {"kana": "リュック", "romaji": "ryukku",  "ru": "рюкзак"},
        {"kana": "チケット", "romaji": "chiketto", "ru": "билет"},
    ],
}

LESSONS = [
    {"id": "k01", "title": "Ряд ア", "subtitle": "a · i · u · e · o", "kana": ["ア", "イ", "ウ", "エ", "オ"],
     "intro": "Катакана — вторая азбука: ей пишут заимствования (コーヒー — кофе), иностранные имена и названия. "
              "Звуки те же, что в хирагане, — учим только новые формы. "
              "Сразу правило долготы: чёрточка ー тянет гласную: カー (kā) — машина."},
    {"id": "k02", "title": "Ряд カ", "subtitle": "ka · ki · ku · ke · ko", "kana": ["カ", "キ", "ク", "ケ", "コ"],
     "intro": "カ — почти хирагана か, а キ — верх от き. С этого урока вы читаете настоящие гайрайго: ケーキ — торт!"},
    {"id": "k03", "title": "Ряд サ", "subtitle": "sa · shi · su · se · so", "kana": ["サ", "シ", "ス", "セ", "ソ"],
     "intro": "Здесь живёт первая пара «катакана-ада»: シ (черты лежат) и ソ (черта стоит). Запомните направление взмаха!"},
    {"id": "k04", "title": "Ряд タ", "subtitle": "ta · chi · tsu · te · to", "kana": ["タ", "チ", "ツ", "テ", "ト"],
     "intro": "Вторая пара ада: ツ (черты стоят, взмах сверху вниз) против シ (черты лежат, взмах снизу вверх)."},
    {"id": "k05", "title": "Ряд ナ", "subtitle": "na · ni · nu · ne · no", "kana": ["ナ", "ニ", "ヌ", "ネ", "ノ"],
     "intro": "ニ — буквально кандзи 二 «два». ノ — одна косая черта."},
    {"id": "k06", "title": "Ряд ハ", "subtitle": "ha · hi · fu · he · ho", "kana": ["ハ", "ヒ", "フ", "ヘ", "ホ"],
     "intro": "ヘ почти не отличается от хираганы へ. Награда урока — слово コーヒー (кофе)!"},
    {"id": "k07", "title": "Ряд マ", "subtitle": "ma · mi · mu · me · mo", "kana": ["マ", "ミ", "ム", "メ", "モ"],
     "intro": "ミ — три штриха. Сравнивайте マ с ア — частая путаница новичков."},
    {"id": "k08", "title": "Ряд ヤ", "subtitle": "ya · yu · yo", "kana": ["ヤ", "ユ", "ヨ"],
     "intro": "ヤ — копия хираганы や. ヨ — грабли зубьями влево (не путайте с ユ)."},
    {"id": "k09", "title": "Ряд ラ", "subtitle": "ra · ri · ru · re · ro", "kana": ["ラ", "リ", "ル", "レ", "ロ"],
     "intro": "リ — копия хираганы り. После этого урока вам откроются ホテル, ミルク и カメラ."},
    {"id": "k10", "title": "Ряд ワ и ン", "subtitle": "wa · wo · n", "kana": ["ワ", "ヲ", "ン"],
     "intro": "Финал базовой катаканы! Третья пара ада: ン (взмах снизу вверх) против ソ (сверху вниз). "
              "ヲ почти не используется — но узнавать его нужно."},
    {"id": "k11", "title": "Дакутэн: ガ и ザ", "subtitle": "ga–go · za–zo", "kana": ["ガ", "ギ", "グ", "ゲ", "ゴ", "ザ", "ジ", "ズ", "ゼ", "ゾ"],
     "intro": "Те же две чёрточки ゛, что в хирагане: カ → ガ, サ → ザ. Новых форм нет — только правило."},
    {"id": "k12", "title": "Дакутэн: ダ и バ", "subtitle": "da–do · ba–bo", "kana": ["ダ", "ヂ", "ヅ", "デ", "ド", "バ", "ビ", "ブ", "ベ", "ボ"],
     "intro": "タ → ダ, ハ → バ. Знаки ヂ и ヅ так же редки, как их родственники в хирагане."},
    {"id": "k13", "title": "Хандакутэн: パ", "subtitle": "pa · pi · pu · pe · po", "kana": ["パ", "ピ", "プ", "ペ", "ポ"],
     "intro": "Кружок ゜: ハ → パ. В гайрайго звук «п» очень частый: パン, パスタ, パンダ."},
    {"id": "k14", "title": "Ёон: キャ・シャ・チャ・ニャ", "subtitle": "kya · sha · cha · nya", "kana": ["キャ", "キュ", "キョ", "シャ", "シュ", "ショ", "チャ", "チュ", "チョ", "ニャ", "ニュ", "ニョ"],
     "intro": "Знак ряда И + маленькие ャュョ — один слог, как в хирагане: ニュース — новости."},
    {"id": "k15", "title": "Ёон: ヒャ・ミャ・リャ", "subtitle": "hya · mya · rya", "kana": ["ヒャ", "ヒュ", "ヒョ", "ミャ", "ミュ", "ミョ", "リャ", "リュ", "リョ"],
     "intro": "Оставшиеся базовые комбинации. В гайрайго встречаются реже, но リュック (рюкзак) без リュ не написать."},
    {"id": "k16", "title": "Ёон с дакутэн", "subtitle": "gya · ja · bya · pya", "kana": ["ギャ", "ギュ", "ギョ", "ジャ", "ジュ", "ジョ", "ビャ", "ビュ", "ビョ", "ピャ", "ピュ", "ピョ"],
     "intro": "Озвонченные комбинации: ジュース (сок), ジャズ (джаз). ジャ/ジュ/ジョ — самые частые."},
    {"id": "k17", "title": "Сокуон и долгота", "subtitle": "ッ · ー", "kana": [], "icon": "ッ",
     "intro": "Маленькое ッ удваивает согласный, как っ в хирагане: カップ (kappu) — чашка. "
              "Долгота в катакане всегда пишется чертой ー: コーヒー, ケーキ. "
              "Вместе они дают целый пласт слов: サッカー — футбол, クッキー — печенье.",
     "rule_lesson": True},
    {"id": "k18", "title": "Катакана-ад", "subtitle": "シツ · ソン · クワフ", "kana": [], "icon": "獄",
     "intro": "Финальный экзамен на различение близнецов (раздел 2.2 методики): シ/ツ, ソ/ン, ク/ワ/フ. "
              "Помните правило: у シ и ン черты/взмах идут СНИЗУ ВВЕРХ, у ツ и ソ — СВЕРХУ ВНИЗ. "
              "Серии быстрых выборов — цель ≥ 95% точности!",
     "rule_lesson": True,
     "drills": [["シ", "ツ"], ["ソ", "ン"], ["ク", "ワ", "フ"], ["チ", "テ"], ["ヌ", "ス"]]},
]
